### PR TITLE
sort mod titles without articles

### LINKED ISSUE #251: Sorting order change of mods list.
Would it be possible to adjust the sorting of mods so that all of the ones whos titles start with "A" or "The" like "A Walk in the Sun" or "The Battle of Neptune", etc. would instead be ordered like library books are "Battle of Neptune, The" and "Walk in the Sun, A" while still displaying the normal title?

As I recall the old Knossos did it that way and it would be good to restore this functionality to Knossos.NET. Otherwise many mods get grouped together right at the start with A or stuffed down in the T section.

### PR DESCRIPTION
**Pull request by Goober5000**
Remove 'A', 'An', and 'The' from the beginning of mod titles before sorting them.  Should fix #251.

I can't actually build and test this at the moment, so this PR is in draft until it can be tested.

### CODE REVIEW

**Comment by Shivansps** [comment]
Im not feeling too well today to try it, i think it should work, but the problem here (and i think this  may be the reason why you cant compile it) is all those removed "usings" on both files, it certanly cant compile without that.

**Comment by Goober5000** [comment]
Well, that's what the IDE recommended, but I've restored all of the `using` statements.  The compilation difficulties are due to some problem with the .NET SDK, so that won't be solved as easily.

**Comment by Shivansps** [comment]
I tested now and it seems to work fine in my tests

**Comment by Goober5000** [comment]
Ah, very good. 👍 Taking it out of draft then.

**Review by Shivansps — APPROVED** [review]

**Pull request merged**
