### PR TITLE
Update Setup Guide

### PR DESCRIPTION
**Pull request by wookieejedi**
Cleanup formatting to avoid varying levels of indentation, fix bug with never ending `waiting for repo.json` bug and cleanup some wording.

### CODE REVIEW

**Comment by wookieejedi** [comment]
Example of update (left old, new right)
image

**Comment by Shivansps** [comment]
I was thinking about, what about adding a HLP discord link at the start of the guide? or maybe the ending

**Comment by wookieejedi** [comment]
Oh yeah that's a good idea! Would you rather it at the start or end? Also, I was wondering about the list of mods, and I almost wonder if it would be better to just have a link to some Google Doc or forum post that explains the campaigns and whatnot, since likely that will be a question many new folks will ask (and have asked before) and the little text box is not long enough to show all the great FSO mod content. 

So in sum:
HLP Discord link for sure, just have to decide at start or end.
Shorten the mod list to simply a link to somewhere else that has as comprehensive guide to mods.

**Comment by JohnAFernandez** [comment]
I think discord link at the beginning is better.  "If at any point you need assistance" type of thing.

**Comment by wookieejedi** [comment]
Yeah at the beginning sounds good.

**Comment by wookieejedi** [comment]
okay got a button added, I think this is ready for review

**Review by Shivansps — APPROVED** [review]
Looks good

**Pull request merged**
