### PR TITLE
Adjust UI Button Colors

### PR DESCRIPTION
**Pull request by JohnAFernandez**
Short video with button changes:

https://github.com/KnossosNET/Knossos.NET/assets/12529946/09032fe0-1d9d-497b-b71b-3d4bb7d1e824

### CODE REVIEW

**Comment by wookieejedi** [comment]
Looks pretty solid. Wonder if ShivanSPS might know how to get buttons to use the white line border?

**Comment by JohnAFernandez** [comment]
For background: the background seemed to disappear after my button changes.

**Comment by Shivansps** [comment]
> Looks pretty solid. Wonder if ShivanSPS might know how to get buttons to use the white line border?

https://github.com/KnossosNET/Knossos.NET/blob/main/Knossos.NET/AppStyles.axaml#L100
Thats the button border color

**Comment by JohnAFernandez** [comment]
Thanks, I just adjusted that, too:

Screen Shot 2023-11-29 at 3 31 47 PM
Screen Shot 2023-11-29 at 3 23 51 PM
Screen Shot 2023-11-29 at 3 23 45 PM

**Pull request merged**
