### PR TITLE
clean up a few UI/UX things

### PR DESCRIPTION
**Pull request by notimaginative**
- Get correct size of retail install
- Fix size of sort order flyout
- Escape underscores used in controls

### CODE REVIEW

**Review by JohnAFernandez — APPROVED** [review]
LGTM

**Comment by notimaginative** [comment]
Ah, didn't realize there was a related bug. It may not actually be fixed by this however, as this change mostly covers places where underscores were converted to "-" instead of just not showing up.

But I'll go through the dev tab better and try to catch all of the areas where this remains a problem.

**Comment by notimaginative** [comment]
Alright, reworked things a bit and the underscores thing should be much better. It now has a converter which can be used on any necessary control to escape underscores. So no need to mess with the source files to fix things (generally) as you can quickly add the converter to the appropriate control in the axml file to get the fix.

I may have missed a some things, so more eyes would be a good idea here. But it should be much easier to fix anything that slips through. And I believe #178 will actually be covered now.

**Comment by wookieejedi** [comment]
Yep in my tests all the underscore display bugs are now fixed, thanks!

**Pull request merged**
