### PR TITLE
Move update/modify to main tab in modcard

### PR DESCRIPTION
**Pull request by Shivansps**
Move Update and Update/Modify to main tab and Fred2 to advanced

### CODE REVIEW

**Comment by Shivansps** [comment]
Ill leave here, maybe someone else had a better idea.

**Comment by wookieejedi** [comment]
Looks good to me

**Review by wookieejedi — APPROVED** [review]
Tested and this change actually works out for the better since now the `Advanced` tab properly shows up for `FS2 Retail`! Excellent.

**Comment by Shivansps** [comment]
It will be needed to add a warning when attemping to delete retail fs2 because that is going to delete ALL MODS that have fs2 as parent.

**Pull request merged**
